### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pnd280** [pnd280/complexity#19]
> [!NOTE]
> This document outlines the planned features and changes - a public development roadmap and **NOT** a final release note. Features and timelines may be subject to change.

## New major features:

- [x] Quick actions command menu
- [ ] Prompt Library
  - Dynamic/Static prompts
  - Prompt chaining
  - Access from external websites
- [ ] Advanced follow-up popup menu
  - Access prompts from the **Prompt Library**
  - Mention (Reply) to part(s) of previous answers #34 
- [ ] Prompt Refiner: interactive UI to improve your prompt #28 
- [ ] Route to other search engines
- [ ] ~~Dedicated Image Generation UI~~
- Enhanced Library View (subject to change)
  - [x] Access everywhere via Popup.
  - [x] Search/Filter threads.
  - [ ] **Folders**: organize threads into folders (can be nested). Dedicated view + display on the sidebar.
  - [ ] Bulk actions: export, delete, move to Spaces, etc. #39 
- [x] Visualize Answers with mind map
  - [x] dedicated option on toolbar
  - [x] `markmap` canvas
- Text-to-speech from the mobile/mac app
  - [ ] play/pause/seek
  - [ ] download
- [ ] ~~Adblock~~

## Others:

- [x] Less hard-coded styles
- [x] More customizable shortcuts
- [x] **Support for all languages** (18) in both Perplexity's interface and the extension UI.
- [ ] AI Profile quick switcher #31 #26 
- [ ] Space thread quick switcher
- More export formats:
  - [ ] JSON
  - [ ] PDF
  - [ ] HTML
- [x] Hide "Related" queries under each answer
- [x] Quickly access previous prompts
- [x] Anonymous toggle/Anonymous mode by default #18 
- [ ] (Bulk) Delete messages other than the last one in a thread #41 
- [x] Light/Dark mode toggle

## FAQs

Early answers to anticipated questions

<details>
<summary>Expand</summary>

### How will the project stay open-source with premium features?

The repository will be periodically rebased with all the free modules/plugins, so that the code base remains transparent and accessible to all.

### What about the free users?

Free users will still be able to use the extension as is, with all the features up to the official transition to the new version.

### What is the pricing model?

- The final pricing model is still under consideration. But expect it to be a monthly subscription model.
- WHY? Complex premium features are designed to enhance the experience for power users (Pro) who are likely already invested in Perplexity monthly. By offering advanced capabilities at a modest additional cost, the extension will provide substantial added value that amplifies the benefits of your existing Perplexity subscription, making it an even more worthwhile investment.

### What about early supporters/contributors?

All those who financially supported the project, regardless of the amount, and those who contributed by reporting bugs/features/ideas (`@Contributor` role on Discord or GitHub issues), will be grandfathered in with extra benefits. Details will be announced later.

### Privacy

Only identifying information will be used for payment.

Premium accounts will be able to sync all extension settings and feature-related data across installations and devices.

Nothing will be shared/used for any purposes.

</details>

**Comment by Classic298** [comment]
Very nice proposal for v1.
If you need any help with the translations, I am sure many of the complexity community would be willing to help with some PRs. Including me.
//EDIT: or with translating the extension itself as well. :)

**Comment by danilofreire** [comment]
I'm happy to help with some translations too! (Portuguese and Spanish)

**Comment by para-droid-ai** [comment]
I'm excited to see what we can really do with CPLXifed Spaces. A quick question though, is there any interest in refining Pages creation? I'd be curious to see if PPLX already has intentions to link them in some way. Having nice Pages for your collections.

**Comment by sickn33** [comment]
i will be very glad to help you with the translation (Italian)

**Comment by Xpos587** [comment]
I could help you with the translation into Russian.

P.S. I am @bertold927 from Discord

**Comment by okamifire** [comment]
Excited for some of the new features described, especially the Export options, some of the visual things, and overall integration.  Not thrilled about a subscription model, but it does make sense with a product being actively developed and improved.

**Comment by pnd280** [comment]
updated the roadmap with a few more features and references

**Comment by peter34245** [comment]
Happy to help with polish translation

**Comment by pnd280** [comment]
I realized that it is impossible to ship all mentioned features/tweaks in one version, so I will move uncompleted items into future iteration plans. From now on Complexity will follow this versioning format: `MAJOR`.`MINOR`.`PATCH`.`BUILD` (with `BUILD` is used for emergency rollbacks)

**Comment by HumanistAtypik** [comment]
👏🏻👏🏻👏🏻 Great!
